### ISSUE TITLE
SUPPORTDATA not implemented

### ISSUE THREAD

**Issue by prettystoopid** [Sinflower/SRPG-ToolBox#1]
While unpacking: "W:\Projects\git_SRPG-ToolBox\SRPG_Unpacker\SRPG_Unpacker\SRPG\Classes\SUPPORTDATA.cpp:52 ERROR This has not been implemented"

**Comment by Sinflower** [comment]
Can you tell me which game you are trying to process so I can implement all the missing classes?

**Comment by prettystoopid** [comment]
Sure - just to clarify, though, it is NSFW. The name is Heelfall.

**Comment by Sinflower** [comment]
Attached is a new version that can properly process the game.
However, I have to note that trying to open the produced SRPGS project in the editor will result in the editor crashing (at least mine crashed when I tried it). The main problem is, that the project is not actually stored in the archive, at least not in its original form, but instead in a modified version. My tool tries to recreate the original file but has a tendency to fail, especially for games made using an older version.

I would need a copy of version 1.226 to figure out how to recreate the correct project file. However, it looks like Steam won't allow me to downgrade the editor. If you know of a way to downgrade the editor, feel free to let me know, and I will try to get you a working project file.

[SRPG_Unpacker.zip](https://github.com/user-attachments/files/17579922/SRPG_Unpacker.zip)

**Comment by Sinflower** [comment]
Update:
Ignore the wall of text above. I forgot to update a version check in the project generator. The version attached can create project files that can be opened in the editor.

[SRPG_Unpacker.zip](https://github.com/user-attachments/files/17580014/SRPG_Unpacker.zip)

**Comment by prettystoopid** [comment]
Awesome, thank you! Seems to open and work fine. Just as a note, when I tried to run via command prompt, I got the errors:
```
Error: Unable to open config file.
Error: Key 'magicNumber' not found.
```
However, running via drag and drop of data.dts worked fine.

**Comment by Sinflower** [comment]
Hmm, that sounds like the tool tried to convert a folder back to a dts file. Did you, by any chance, provide a folder name instead of the dts file? E.g.:
`SRPG_Unpacker.exe data`
instead of
`SRPG_Unpacker.exe data.dts`
